### ISSUE TITLE
4.17 compatibility

### ISSUE THREAD

**Issue by centrifical** [tomlooman/StealthGameUdemy#1]
Hi Tom I signed up for your class came to download this and Its for 4.18 which in your tutorial you say to use 4.17 can you please update a 4.17 version of the project file thanks.

**Comment by semaph0r** [comment]
@centrifical Is there currently a breaking change in the API of 4.18, which may prevent you from using it?

**Comment by tomlooman** [comment]
Sorry for not seeing this sooner. It was indeed an oversight on my end due to recording order back then. The project is 4.18 only unfortunately (only due to content loading, the project lectures can still be followed from 4.17 as I updated all content packs to use 4.17 instead just after the course originally launched)
